// ─── Type Definition ──────────────────────────────────────────────────────────
export type Product = {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
  category: "Building Materials" | "Sanitary" | "Safety";
  rating: number;
  reviews: number;
  href: string;
  discount?: string;
  variants?: string;
  price?: number;
};

// ─── Data ─────────────────────────────────────────────────────────────────────
// t diambil dari useTranslations("Products") di komponen yang memanggilnya
const getProducts = (t: (key: string) => string): Product[] => [
  {
    id: 1,
    name: "Servvo",
    slug: "servvo",
    description: t("servvo_desc"),
    image: "/produk/SERVVO.png",
    category: "Safety",
    rating: 4.9,
    reviews: 210,
    discount: "",
    variants: "8 Items",
    href: "/produk/servvo",
  },
  {
    id: 2,
    name: "Semen Merahputih",
    slug: "semenmerahputih",
    image: "/produk/SEMEN MERAH PUTIH.png",
    description: t("semenmerahputih_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 175,
    discount: "",
    variants: "4 Items",
    href: "/produk/semenmerahputih",
  },
  {
    id: 3,
    name: "Wavin",
    slug: "wavin",
    price: 129900,
    image: "/produk/WAVIN.png",
    description: t("wavin_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 165,
    discount: "",
    variants: "6 Items",
    href: "/produk/wavin",
  },
  {
    id: 4,
    name: "Trilliun Hose",
    slug: "trilliun",
    image: "/produk/TRILLIUN.png",
    description: t("trilliunhose_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 236,
    discount: "",
    variants: "5 Items",
    href: "/produk/trilliun",
  },
  {
    id: 5,
    name: "Trilliunware",
    slug: "trilliunware",
    image: "/produk/TRILLIUNWARE.png",
    description: t("trilliunware_desc"),
    category: "Sanitary",
    rating: 5,
    reviews: 340,
    variants: "8 Items",
    href: "/produk/trilliunware",
  },
  {
    id: 6,
    name: "Tokka",
    slug: "tokka",
    image: "/produk/TOKKAA.png",
    description: t("tokka_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "3 Items",
    href: "/produk/tokka",
  },
  {
    id: 7,
    name: "Dulux",
    slug: "dulux",
    image: "/produk/DULUXX.png",
    description: t("dulux_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 330,
    variants: "8 Items",
    href: "/produk/dulux",
  },
  {
    id: 8,
    name: "Superex",
    slug: "superex",
    image: "/produk/SUPEREXX.png",
    description: t("superex_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "3 Items",
    href: "/produk/superex",
  },
  {
    id: 9,
    name: "Yoshino Gypsum",
    slug: "yoshino",
    image: "/produk/YOSHINOO.png",
    description: t("yoshino_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "1 Items",
    href: "/produk/yoshino",
  },
  {
    id: 10,
    name: "Aquaproof",
    slug: "aquaproof",
    image: "/produk/AQUAPROOFF.png",
    description: t("aquaproof_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "4 Items",
    href: "/produk/aquaproof",
  },
  {
    id: 11,
    name: "Bildo",
    slug: "bildo",
    image: "/produk/BILDOO.png",
    description: t("bildo_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "1 Items",
    href: "/produk/bildo",
  },
  {
    id: 12,
    name: "Dcota",
    slug: "dcota",
    image: "/produk/DCOTAA.png",
    description: t("dcota_desc"),
    category: "Sanitary",
    rating: 5,
    reviews: 340,
    variants: "5 Items",
    href: "/produk/dcota",
  },
  {
    id: 13,
    name: "SLG",
    slug: "slg",
    image: "/produk/SLGG.png",
    description: t("slg_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "5 Items",
    href: "/produk/slg",
  },
  {
    id: 14,
    name: "Supreme",
    slug: "supreme",
    image: "/produk/SUPREMEE.png",
    description: t("supreme_desc"),
    category: "Building Materials",
    rating: 5,
    reviews: 340,
    variants: "7 Items",
    href: "/produk/supreme",
  },
];

export default getProducts;
